"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

### --- ADJUST VERSION --- ###
VERSION = '1.0.3'
### ---------------------- ###

APP = ['../pod5Viewer/__main__.py']
APP_NAME = 'pod5Viewer'
DATA_FILES = []

OPTIONS = {
    'iconfile': 'icon.icns',
    'plist': {
        'CFBundleName' : APP_NAME,
        'CFBundleShortVersionString' : VERSION,
        'CFBundleIdentifier': 'com.example.pod5Viewer',
        'CFBundleDevelopmentRegion': 'English',
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': 'pod5Viewer ' + VERSION,
        'CFBundleExecutable': APP_NAME,
        'CFBundlePackageType': 'APPL',
        'NSPrincipalClass': 'NSApplication',
        'UTExportedTypeDeclarations': [
            {
                'UTTypeIdentifier': 'com.example.pod5',
                'UTTypeDescription': 'POD5 File',
                'UTTypeConformsTo': ['public.data'],
                'UTTypeTagSpecification': {
                    'public.filename-extension': ['pod5'],
                    'public.mime-type': ['application/x-pod5'],
                },
            }
        ],
        'CFBundleDocumentTypes': [
            {
                'CFBundleTypeName': 'POD5 File',
                'CFBundleRole': 'Viewer',
                'LSItemContentTypes': ['com.example.pod5'],
                'CFBundleTypeExtensions': ['pod5'],
                'CFBundleTypeIconFile': 'icon.icns'
            },
        ],
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
